name = "10xn-flashcards"
compatibility_date = "2025-01-20"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "7e2775f3d3344aada779ae8f262ea1e0"
preview_id = "b757d9fcf13445f1bc171ee3db81dc60"

[build]
command = "npm run build"

[observability.logs]
enabled = true

[vars]

[env.production.vars]
# Production environment variables will be set in Cloudflare Dashboard
ENVIRONMENT = "production"

[env.preview.vars] 
# Preview environment variables for staging deployments
ENVIRONMENT = "preview"